# Generated by Django 6.0.3 on 2026-05-05 11:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата')),
                ('department', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Кафедра')),
                ('academic_degree', models.CharField(blank=True, choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Кандидат наук'), ('doctor', 'Доктор наук')], default=None, max_length=50, null=True, verbose_name='Ученая степень')),
                ('office_hours', models.CharField(blank=True, default=None, help_text='Например: Пн-Пт 10:00-12:00', max_length=100, null=True, verbose_name='Часы приема')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'unique_together': {('first_name', 'last_name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Кредиты')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('duration_weeks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность (недель)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('max_students', models.PositiveIntegerField(blank=True, default=30, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальное количество студентов')),
                ('syllabus', models.TextField(blank=True, default=None, null=True, verbose_name='Учебный план')),
                ('prerequisites', models.TextField(blank=True, default=None, null=True, verbose_name='Предварительные требования')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн курс')),
                ('start_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата начала курса')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'unique_together': {('title', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('education', models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование')),
                ('experience_years', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Опыт работы (лет)')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('office_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер кабинета')),
                ('passport_number', models.CharField(blank=True, default=None, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}\\s?\\d{6}$', message='Введите паспорт в формате: 1234 567890')], verbose_name='Серия и номер паспорта')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Холост/Не замужем'), ('married', 'Женат/Замужем'), ('divorced', 'Разведен/Разведена')], default=None, max_length=20, null=True, verbose_name='Семейное положение')),
                ('publications_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество публикаций')),
                ('emergency_contact', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Экстренный контакт')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Информация о преподавателе',
                'verbose_name_plural': 'Информация о преподавателях',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Дата зачисления')),
                ('student_id', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Номер студенческого билета')),
                ('group_number', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Номер группы')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Средний балл')),
                ('scholarship', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стипендия')),
                ('graduation_year', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)], verbose_name='Год выпуска')),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='schedule.course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'unique_together': {('first_name', 'last_name', 'email')},
            },
        ),
    ]
