# Generated by Django 6.0.3 on 2026-04-18 08:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='office_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер кабинета'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='schedule.teacher', verbose_name='Преподаватель'),
        ),
    ]
